name: OMS CI
on:
  push:
    branches: [ feature/arm-build ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: OMSAgent Build & Test
    runs-on: self-hosted

    steps:
    - name: Checkout OMS-Agent-For-Linux Repo
      uses: actions/checkout@v2
      with:
        path: Main
        submodules: true
